### ISSUE TITLE
script scanSource.py fails during map-making

### ISSUE THREAD

**Issue by planck2007** [mousset/qubic#11]
If I run the script scanSource.py present in the qubic/qubic/doc folder the script dies at line 139. The error message is:
Traceback (most recent call last):
  File "scanSource.py", line 139, in <module>
    TOD_useless, maps_convolved = arec.get_observation(x0)
  File "/home/daniele/.conda/envs/qubic_env/lib/python3.6/site-packages/qubic/acquisition.py", line 430, in get_observation
    map = convolution(map)
  File "/home/daniele/.conda/envs/qubic_env/lib/python3.6/site-packages/pyoperators-0.13.12.post1-py3.6-linux-x86_64.egg/pyoperators/core.py", line 350, in __call__
    i, i_, o, o_ = self._validate_arguments(x, out)
  File "/home/daniele/.conda/envs/qubic_env/lib/python3.6/site-packages/pyoperators-0.13.12.post1-py3.6-linux-x86_64.egg/pyoperators/core.py", line 1163, in _validate_arguments
    shapein, shapeout = self._validate_shapes(input.shape, shapeout)
  File "/home/daniele/.conda/envs/qubic_env/lib/python3.6/site-packages/pyoperators-0.13.12.post1-py3.6-linux-x86_64.egg/pyoperators/core.py", line 1217, in _validate_shapes
    self.validatein(shapein)
  File "/home/daniele/.conda/envs/qubic_env/lib/python3.6/site-packages/pysimulators-1.1.dev100-py3.6-linux-x86_64.egg/pysimulators/interfaces/healpy/operators.py", line 295, in validatein
    raise ValueError('Invalid number of dimensions.')
ValueError: Invalid number of dimensions.

**Comment by mousset** [comment]
Yes you are right, I have the same error. I think it comes from a missmatch between monoband and multiband. I think I will split this script in two, one for the monoband case and one for the multiband case.
